FROM harbor.galasa.dev/redhat_proxy_cache/ubi8/httpd-24:1-345

ARG directory

COPY isolated/dockerfiles/httpdconf/httpd.conf /etc/httpd/conf/httpd.conf

COPY ${directory}/target/isolated/ /var/www/html/